# Generated by Django 3.0.8 on 2020-07-05 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='habilitado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='pontuacao',
        ),
    ]
