# Generated by Django 3.0.8 on 2020-07-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0002_auto_20200705_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
